<?xml version="1.0"?>
<package format="3">
  <name>scan_data_gazebo_sim</name>
  <description>Gazebo + ROS 2 simulation for generating 2D LiDAR scan-matching datasets with ground-truth poses.</description>

  <version>0.1.0</version>
  <license>MIT</license>
  <author>Tim Hansen</author>
  <maintainer email="tim@example.com">Tim Hansen</maintainer>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
