"""Launch Gazebo Harmonic with a maze world and spawn the simple robot.

By default the LiDAR scan is generated by Gazebo's native gpu_lidar sensor
(lidar_mode:=gazebo), the sim runs headless (headless:=true, no Gazebo GUI —
safe on Wayland/no-GPU), and RViz is started for visualization (use_rviz:=true).

Falls back to the Python CPU raycaster with lidar_mode:=cpu if the native
sensor fails to initialise on a headless/no-GPU machine.

Usage:
    ros2 launch scan_data_gazebo_sim sim.launch.py
    ros2 launch scan_data_gazebo_sim sim.launch.py lidar_mode:=cpu
    ros2 launch scan_data_gazebo_sim sim.launch.py headless:=false use_rviz:=false
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, SetEnvironmentVariable
from launch.substitutions import (
    LaunchConfiguration, PathJoinSubstitution, PythonExpression
)
from launch.conditions import IfCondition
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node


def generate_launch_description():
    pkg = "scan_data_gazebo_sim"

    world_arg = DeclareLaunchArgument(
        "world",
        default_value="maze_small",
        description="Name of the maze world (without .sdf extension)",
    )

    bridge_arg = DeclareLaunchArgument(
        "use_ros_gz_bridge",
        default_value="true",
        description="Whether to start the ROS-Gazebo bridge",
    )

    lidar_mode_arg = DeclareLaunchArgument(
        "lidar_mode",
        default_value="gazebo",
        description="Scan source: 'gazebo' (native gpu_lidar) or 'cpu' (Python raycaster fallback)",
    )

    # lidar_mode == 'gazebo' / 'cpu' as boolean substitutions for IfCondition
    use_gazebo_lidar = PythonExpression(
        ["'", LaunchConfiguration("lidar_mode"), "' == 'gazebo'"]
    )
    use_cpu_lidar = PythonExpression(
        ["'", LaunchConfiguration("lidar_mode"), "' == 'cpu'"]
    )

    headless_arg = DeclareLaunchArgument(
        "headless",
        default_value="false",
        description="true = server only (no Gazebo GUI, safe on Wayland/no-GPU); false = server + GUI",
    )

    use_rviz_arg = DeclareLaunchArgument(
        "use_rviz",
        default_value="false",
        description="Start RViz for scan visualization (odom->chassis->laser TF + /scan)",
    )

    use_rviz = PythonExpression(["'", LaunchConfiguration("use_rviz"), "' == 'true'"])
    use_headless = PythonExpression(["'", LaunchConfiguration("headless"), "' == 'true'"])
    use_gui = PythonExpression(["'", LaunchConfiguration("headless"), "' != 'true'"])

    # Point Gazebo to the model directory so model://simple_robot resolves
    gz_resource_path = SetEnvironmentVariable(
        name="GZ_SIM_RESOURCE_PATH",
        value=PathJoinSubstitution([FindPackageShare(pkg), "description"]),
    )

    # Append .sdf extension via PythonExpression substitution
    world_file = PythonExpression(["'", LaunchConfiguration("world"), "' + '.sdf'"])

    # Gazebo server — headless (no GUI, default; safe on Wayland/no-GPU) or with GUI
    gz_server_headless = ExecuteProcess(
        cmd=[
            "gz", "sim", "-s", "-r", "-v", "3",
            PathJoinSubstitution([FindPackageShare(pkg), "worlds", world_file]),
        ],
        output="screen",
        condition=IfCondition(use_headless),
    )
    gz_server_gui = ExecuteProcess(
        cmd=[
            "gz", "sim", "-r", "-v", "3",
            PathJoinSubstitution([FindPackageShare(pkg), "worlds", world_file]),
        ],
        output="screen",
        condition=IfCondition(use_gui),
    )

    # Bridge (always-on): ROS 2 <-> Gazebo for clock, cmd_vel, odom, model pose.
    # /clock is REQUIRED for use_sim_time nodes (RViz, TF) — without it ROS
    # time stays at 0 and RViz cannot resolve the sim-time-stamped transforms.
    bridge = ExecuteProcess(
        cmd=[
            "ros2", "run", "ros_gz_bridge", "parameter_bridge",
            "/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock",
            "/cmd_vel@geometry_msgs/msg/Twist@gz.msgs.Twist",
            "/odom@nav_msgs/msg/Odometry@gz.msgs.Odometry",
            "/model/simple_robot/pose@geometry_msgs/msg/PoseStamped@gz.msgs.Pose",
        ],
        output="screen",
        condition=IfCondition(LaunchConfiguration("use_ros_gz_bridge")),
    )

    # Bridge (gated): scan topic — only when using Gazebo's native gpu_lidar
    scan_bridge = ExecuteProcess(
        cmd=[
            "ros2", "run", "ros_gz_bridge", "parameter_bridge",
            "/scan@sensor_msgs/msg/LaserScan@gz.msgs.LaserScan",
        ],
        output="screen",
        condition=IfCondition(PythonExpression(
            ["'", LaunchConfiguration("use_ros_gz_bridge"), "' == 'true' and '",
             LaunchConfiguration("lidar_mode"), "' == 'gazebo'"]
        )),
    )

    # CPU raycaster (fallback): reads robot pose from /odom, publishes /scan
    raycaster = Node(
        package="scan_data_gazebo_sim",
        executable="raycaster",
        name="raycaster",
        output="screen",
        parameters=[{
            "use_sim_time": True,
            "world": LaunchConfiguration("world"),
        }],
        condition=IfCondition(use_cpu_lidar),
    )

    # Ground truth: subscribes to Gazebo model pose (bridged), publishes /ground_truth_pose
    ground_truth = Node(
        package="scan_data_gazebo_sim",
        executable="ground_truth",
        name="ground_truth_publisher",
        output="screen",
        parameters=[{"use_sim_time": True}],
    )

    # RViz visualization (gated by use_rviz): odom->chassis TF from /odom,
    # chassis->laser static TF, and RViz with /scan loaded.
    tf_broadcaster = Node(
        package="scan_data_gazebo_sim",
        executable="tf_broadcaster",
        name="odom_tf_broadcaster",
        output="screen",
        parameters=[{"use_sim_time": True}],
        condition=IfCondition(use_rviz),
    )
    static_tf = Node(
        package="tf2_ros",
        executable="static_transform_publisher",
        name="static_tf_chassis_laser",
        arguments=["0", "0", "0.12", "0", "0", "0", "chassis", "laser"],
        condition=IfCondition(use_rviz),
    )
    # RViz with the scan-viz config. use_sim_time must match the sim:
    # TF and /scan stamps are sim time — with wall time RViz considers
    # every frame ~56 years stale ("frame odom does not exist", no laser).
    # (The earlier camera-freeze was a config issue — missing Tools
    # section — now fixed in scan_viz.rviz.)
    rviz = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        arguments=["-d", PathJoinSubstitution(
            [FindPackageShare(pkg), "config", "scan_viz.rviz"])],
        parameters=[{"use_sim_time": True}],
        condition=IfCondition(use_rviz),
    )

    return LaunchDescription([
        world_arg,
        bridge_arg,
        lidar_mode_arg,
        headless_arg,
        use_rviz_arg,
        gz_resource_path,
        gz_server_headless,
        gz_server_gui,
        bridge,
        scan_bridge,
        raycaster,
        ground_truth,
        tf_broadcaster,
        static_tf,
        rviz,
    ])
