"""Launch Gazebo Harmonic with a maze world and spawn the simple robot.

By default the LiDAR scan is generated by Gazebo's native gpu_lidar sensor
(lidar_mode:=gazebo). If that fails on a headless/no-GPU machine, fall back
to the Python CPU raycaster with lidar_mode:=cpu (no rebuild needed).

Usage:
    ros2 launch scan_data_gazebo_sim sim.launch.py world:=maze_small
    ros2 launch scan_data_gazebo_sim sim.launch.py lidar_mode:=cpu
"""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, SetEnvironmentVariable
from launch.substitutions import (
    LaunchConfiguration, PathJoinSubstitution, PythonExpression
)
from launch.conditions import IfCondition
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node


def generate_launch_description():
    pkg = "scan_data_gazebo_sim"

    world_arg = DeclareLaunchArgument(
        "world",
        default_value="maze_small",
        description="Name of the maze world (without .sdf extension)",
    )

    bridge_arg = DeclareLaunchArgument(
        "use_ros_gz_bridge",
        default_value="true",
        description="Whether to start the ROS-Gazebo bridge",
    )

    lidar_mode_arg = DeclareLaunchArgument(
        "lidar_mode",
        default_value="gazebo",
        description="Scan source: 'gazebo' (native gpu_lidar) or 'cpu' (Python raycaster fallback)",
    )

    # lidar_mode == 'gazebo' / 'cpu' as boolean substitutions for IfCondition
    use_gazebo_lidar = PythonExpression(
        ["'", LaunchConfiguration("lidar_mode"), "' == 'gazebo'"]
    )
    use_cpu_lidar = PythonExpression(
        ["'", LaunchConfiguration("lidar_mode"), "' == 'cpu'"]
    )

    # Point Gazebo to the model directory so model://simple_robot resolves
    gz_resource_path = SetEnvironmentVariable(
        name="GZ_SIM_RESOURCE_PATH",
        value=PathJoinSubstitution([FindPackageShare(pkg), "description"]),
    )

    # Append .sdf extension via PythonExpression substitution
    world_file = PythonExpression(["'", LaunchConfiguration("world"), "' + '.sdf'"])

    # Gazebo server + GUI-less sim (Sensors plugin loaded by the world SDF)
    gz_server = ExecuteProcess(
        cmd=[
            "gz", "sim", "-r", "-v", "3",
            PathJoinSubstitution([FindPackageShare(pkg), "worlds", world_file]),
        ],
        output="screen",
    )

    # Bridge (always-on): ROS 2 <-> Gazebo for cmd_vel, odom, and model pose
    bridge = ExecuteProcess(
        cmd=[
            "ros2", "run", "ros_gz_bridge", "parameter_bridge",
            "/cmd_vel@geometry_msgs/msg/Twist@gz.msgs.Twist",
            "/odom@nav_msgs/msg/Odometry@gz.msgs.Odometry",
            "/model/simple_robot/pose@geometry_msgs/msg/PoseStamped@gz.msgs.Pose",
        ],
        output="screen",
        condition=IfCondition(LaunchConfiguration("use_ros_gz_bridge")),
    )

    # Bridge (gated): scan topic — only when using Gazebo's native gpu_lidar
    scan_bridge = ExecuteProcess(
        cmd=[
            "ros2", "run", "ros_gz_bridge", "parameter_bridge",
            "/scan@sensor_msgs/msg/LaserScan@gz.msgs.LaserScan",
        ],
        output="screen",
        condition=IfCondition(PythonExpression(
            ["'", LaunchConfiguration("use_ros_gz_bridge"), "' == 'true' and '",
             LaunchConfiguration("lidar_mode"), "' == 'gazebo'"]
        )),
    )

    # CPU raycaster (fallback): reads robot pose from /odom, publishes /scan
    raycaster = Node(
        package="scan_data_gazebo_sim",
        executable="raycaster",
        name="raycaster",
        output="screen",
        parameters=[{
            "use_sim_time": True,
            "world": LaunchConfiguration("world"),
        }],
        condition=IfCondition(use_cpu_lidar),
    )

    # Ground truth: subscribes to Gazebo model pose (bridged), publishes /ground_truth_pose
    ground_truth = Node(
        package="scan_data_gazebo_sim",
        executable="ground_truth",
        name="ground_truth_publisher",
        output="screen",
        parameters=[{"use_sim_time": True}],
    )

    return LaunchDescription([
        world_arg,
        bridge_arg,
        lidar_mode_arg,
        gz_resource_path,
        gz_server,
        bridge,
        scan_bridge,
        raycaster,
        ground_truth,
    ])
